spring.application.name=comicreader

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/comicreader
spring.datasource.username=postgres
spring.datasource.password=Ragav@0615

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=300MB

comic.upload-dir=uploads