spring.application.name=comicreader

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/comicreader}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=300MB

comic.uploadDir=${COMIC_UPLOAD_DIR:uploads}